Updated the new S3 bucket names with wheel packaging update to v1.0.0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,20 +27,20 @@ jobs:
             mkdir -p /tmp/conda-bld/linux-64
             
             # Download noarch and linux-64 with error handling
-            aws s3 cp s3://ocpipes-prod/noarch /tmp/conda-bld/noarch --recursive || {
+            aws s3 cp s3://ds-conda-builds/ocpipes/noarch /tmp/conda-bld/noarch --recursive || {
               echo 'Failed to download files from noarch directory. Using default empty directory.';
               mkdir -p /tmp/conda-bld/noarch
             }
-            aws s3 cp s3://ocpipes-prod/linux-64 /tmp/conda-bld/linux-64 --recursive || {
+            aws s3 cp s3://ds-conda-builds/ocpipes/linux-64 /tmp/conda-bld/linux-64 --recursive || {
               echo 'Failed to download files from noarch directory. Using default empty directory.';
               mkdir -p /tmp/conda-bld/linux-64
             }
             
             # Download index.html with error handling
-            aws s3 cp s3://ocpipes-prod/index.html /tmp/conda-bld/index.html || { echo 'Failed to download index.html. Using default empty file.'; echo '{}' > /tmp/conda-bld/index.html; }
+            aws s3 cp s3://ds-conda-builds/ocpipes/index.html /tmp/conda-bld/index.html || { echo 'Failed to download index.html. Using default empty file.'; echo '{}' > /tmp/conda-bld/index.html; }
             
             # Download channeldata.json with error handling
-            aws s3 cp s3://ocpipes-prod/channeldata.json /tmp/conda-bld/channeldata.json || { echo 'Failed to download channeldata.json. Using default empty file.'; echo '{}' > /tmp/conda-bld/channeldata.json; }
+            aws s3 cp s3://ds-conda-builds/ocpipes/channeldata.json /tmp/conda-bld/channeldata.json || { echo 'Failed to download channeldata.json. Using default empty file.'; echo '{}' > /tmp/conda-bld/channeldata.json; }
 
             echo "Downloaded files from S3."
       - run:
@@ -164,19 +164,19 @@ jobs:
           command: |
 
             echo "Uploading repodata files back to S3"
-            aws s3 cp /tmp/conda-bld/noarch/repodata.json s3://ocpipes-prod/noarch/repodata.json
-            aws s3 cp /tmp/conda-bld/noarch/current_repodata.json s3://ocpipes-prod/noarch/current_repodata.json
-            aws s3 cp /tmp/conda-bld/noarch/index.html s3://ocpipes-prod/noarch/index.html
-            aws s3 cp /tmp/conda-bld/linux-64/repodata.json s3://ocpipes-prod/linux-64/repodata.json
-            aws s3 cp /tmp/conda-bld/linux-64/current_repodata.json s3://ocpipes-prod/linux-64/current_repodata.json
-            aws s3 cp /tmp/conda-bld/linux-64/index.html s3://ocpipes-prod/linux-64/index.html
+            aws s3 cp /tmp/conda-bld/noarch/repodata.json s3://ds-conda-builds/ocpipes/noarch/repodata.json
+            aws s3 cp /tmp/conda-bld/noarch/current_repodata.json s3://ds-conda-builds/ocpipes/noarch/current_repodata.json
+            aws s3 cp /tmp/conda-bld/noarch/index.html s3://ds-conda-builds/ocpipes/noarch/index.html
+            aws s3 cp /tmp/conda-bld/linux-64/repodata.json s3://ds-conda-builds/ocpipes/linux-64/repodata.json
+            aws s3 cp /tmp/conda-bld/linux-64/current_repodata.json s3://ds-conda-builds/ocpipes/linux-64/current_repodata.json
+            aws s3 cp /tmp/conda-bld/linux-64/index.html s3://ds-conda-builds/ocpipes/linux-64/index.html
             echo "Uploading channeldata file back to S3"
-            aws s3 cp /tmp/conda-bld/channeldata.json s3://ocpipes-prod/channeldata.json
+            aws s3 cp /tmp/conda-bld/channeldata.json s3://ds-conda-builds/ocpipes/channeldata.json
 
             PACKAGE_PATH_LATEST=$(find /tmp/conda-bld/noarch/ -name 'ocpipes-*.tar.bz2' | sort -V | tail -n 1)
             PACKAGE_FILENAME=$(basename "$PACKAGE_PATH_LATEST")
             echo "Uploading Conda packages to S3..."
-            aws s3 cp "/tmp/conda-bld/noarch/$PACKAGE_FILENAME" s3://ocpipes-prod/noarch/
+            aws s3 cp "/tmp/conda-bld/noarch/$PACKAGE_FILENAME" s3://ds-conda-builds/ocpipes/noarch/
 
   build_and_upload_wheel:
     docker:
@@ -206,7 +206,7 @@ jobs:
             . venv/bin/activate
             WHEEL_FILE=$(ls ocpipes/dist/*.whl)
             echo "Uploading $WHEEL_FILE to S3"
-            aws s3 cp "$WHEEL_FILE" s3://ocpipes-artifactory-prod/
+            aws s3 cp "$WHEEL_FILE" s3://ds-python-wheels/ocpipes/
 
 workflows:
   build-pipeline:
